// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.BatchProcessing
{
    /// <summary>The workflow type for the batch process</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchProcessingPostRequestBody
    {
        [EnumMember(Value = "create-and-screen")]
        #pragma warning disable CS1591
        CreateAndScreen,
        #pragma warning restore CS1591
        [EnumMember(Value = "create-and-monitor")]
        #pragma warning disable CS1591
        CreateAndMonitor,
        #pragma warning restore CS1591
    }
}
