// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.Cases
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCustomerRisk_levelQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "LOW")]
        #pragma warning disable CS1591
        LOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEDIUM")]
        #pragma warning disable CS1591
        MEDIUM,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGH")]
        #pragma warning disable CS1591
        HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROHIBITED")]
        #pragma warning disable CS1591
        PROHIBITED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SKIPPED")]
        #pragma warning disable CS1591
        SKIPPED,
        #pragma warning restore CS1591
    }
}
