// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.Notifications.Configurations.Email
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CASE_ASSIGNED")]
        #pragma warning disable CS1591
        CASE_ASSIGNED,
        #pragma warning restore CS1591
    }
}
