// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\entity-screening\risks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RisksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the PayNow.Libraries.ComplyAdvantageClient.v2.entityScreening.risks.item collection</summary>
        /// <param name="position">The unique risk identifier</param>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item.WithRisk_identifierItemRequestBuilder"/></returns>
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item.WithRisk_identifierItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("risk_identifier", position);
                return new global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item.WithRisk_identifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the PayNow.Libraries.ComplyAdvantageClient.v2.entityScreening.risks.item collection</summary>
        /// <param name="position">The unique risk identifier</param>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item.WithRisk_identifierItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item.WithRisk_identifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("risk_identifier", position);
                return new global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.Item.WithRisk_identifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.RisksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RisksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/entity-screening/risks", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.EntityScreening.Risks.RisksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RisksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/entity-screening/risks", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
