// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.V2.RegulatoryReports.PrefillInformation.Fincen.Sar.FinancialInstitutions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.RegulatoryReports.PrefillInformation.Fincen.Sar
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\regulatory-reports\prefill-information\fincen\sar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SarRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The financialInstitutions property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.RegulatoryReports.PrefillInformation.Fincen.Sar.FinancialInstitutions.FinancialInstitutionsRequestBuilder FinancialInstitutions
        {
            get => new global::PayNow.Libraries.ComplyAdvantageClient.V2.RegulatoryReports.PrefillInformation.Fincen.Sar.FinancialInstitutions.FinancialInstitutionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.RegulatoryReports.PrefillInformation.Fincen.Sar.SarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SarRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/regulatory-reports/prefill-information/fincen/sar", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.RegulatoryReports.PrefillInformation.Fincen.Sar.SarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SarRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/regulatory-reports/prefill-information/fincen/sar", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
