// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PostRescreen_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DELTA")]
        #pragma warning disable CS1591
        DELTA,
        #pragma warning restore CS1591
    }
}
