// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\customers\{customer_identifier}\workflows\sync\rescreen
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RescreenRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RescreenRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/customers/{customer_identifier}/workflows/sync/rescreen{?rescreen_type*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RescreenRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/customers/{customer_identifier}/workflows/sync/rescreen{?rescreen_type*}", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint initiates the synchronous &apos;rescreen&apos; workflow for your customer. The workflow consists of two steps:1. **Customer Rescreening:** The customer is screened against the latest data sources to identify any new risk information.2. **Alerting:** If new, relevant, risks are found an alert is generated. The workflow executes synchronously, returning the workflow status and result immediately.The rescreening operation applies the rules and settings defined in the customer&apos;s monitoring configuration. If no monitoring configuration is currently assigned to the customer, the system will default to using the initial screening configuration applied when the customer was first screened. Rescreen events count towards your total onboarding search volumes You need &quot;Account has access to monitor on demand functionality&quot; enabled to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_WorkflowState"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ProblemDetailErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_WorkflowState?> PostAsync(Action<RequestConfiguration<global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder.RescreenRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_WorkflowState> PostAsync(Action<RequestConfiguration<global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder.RescreenRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ProblemDetailErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_WorkflowState>(requestInfo, global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_WorkflowState.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint initiates the synchronous &apos;rescreen&apos; workflow for your customer. The workflow consists of two steps:1. **Customer Rescreening:** The customer is screened against the latest data sources to identify any new risk information.2. **Alerting:** If new, relevant, risks are found an alert is generated. The workflow executes synchronously, returning the workflow status and result immediately.The rescreening operation applies the rules and settings defined in the customer&apos;s monitoring configuration. If no monitoring configuration is currently assigned to the customer, the system will default to using the initial screening configuration applied when the customer was first screened. Rescreen events count towards your total onboarding search volumes You need &quot;Account has access to monitor on demand functionality&quot; enabled to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder.RescreenRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder.RescreenRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder WithUrl(string rawUrl)
        {
            return new global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// This endpoint initiates the synchronous &apos;rescreen&apos; workflow for your customer. The workflow consists of two steps:1. **Customer Rescreening:** The customer is screened against the latest data sources to identify any new risk information.2. **Alerting:** If new, relevant, risks are found an alert is generated. The workflow executes synchronously, returning the workflow status and result immediately.The rescreening operation applies the rules and settings defined in the customer&apos;s monitoring configuration. If no monitoring configuration is currently assigned to the customer, the system will default to using the initial screening configuration applied when the customer was first screened. Rescreen events count towards your total onboarding search volumes You need &quot;Account has access to monitor on demand functionality&quot; enabled to use this endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RescreenRequestBuilderPostQueryParameters 
        {
            /// <summary>Specifies the screening logic to apply. Set to DELTA to perform a differential screen, which compares the new result against the customer&apos;s previous screening baseline and only alerts on new or changed risk factors.</summary>
            [Obsolete("This property is deprecated, use RescreenTypeAsPostRescreenTypeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("rescreen_type")]
            public string? RescreenType { get; set; }
#nullable restore
#else
            [QueryParameter("rescreen_type")]
            public string RescreenType { get; set; }
#endif
            /// <summary>Specifies the screening logic to apply. Set to DELTA to perform a differential screen, which compares the new result against the customer&apos;s previous screening baseline and only alerts on new or changed risk factors.</summary>
            [QueryParameter("rescreen_type")]
            public global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.PostRescreen_typeQueryParameterType? RescreenTypeAsPostRescreenTypeQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RescreenRequestBuilderPostRequestConfiguration : RequestConfiguration<global::PayNow.Libraries.ComplyAdvantageClient.V2.Customers.Item.Workflows.Sync.Rescreen.RescreenRequestBuilder.RescreenRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
