// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.Transaction.LookupListMappings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.Transaction
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\enrichment\transaction
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lookupListMappings property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.Transaction.LookupListMappings.LookupListMappingsRequestBuilder LookupListMappings
        {
            get => new global::PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.Transaction.LookupListMappings.LookupListMappingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.Transaction.TransactionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/enrichment/transaction", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.Transaction.TransactionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/enrichment/transaction", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
