// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.V2.Cases.Notes.Bulk;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.Cases.Notes
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\cases\notes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bulk property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.Cases.Notes.Bulk.BulkRequestBuilder Bulk
        {
            get => new global::PayNow.Libraries.ComplyAdvantageClient.V2.Cases.Notes.Bulk.BulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Cases.Notes.NotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/cases/notes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Cases.Notes.NotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NotesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/cases/notes", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
