// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\alerts\mutes\{alert_mute_key}\customer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the PayNow.Libraries.ComplyAdvantageClient.v2.alerts.mutes.item.customer.item collection</summary>
        /// <param name="position">UUID Identifier for the Customer</param>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item.WithCustomer_identifierItemRequestBuilder"/></returns>
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item.WithCustomer_identifierItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("customer_identifier", position);
                return new global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item.WithCustomer_identifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the PayNow.Libraries.ComplyAdvantageClient.v2.alerts.mutes.item.customer.item collection</summary>
        /// <param name="position">UUID Identifier for the Customer</param>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item.WithCustomer_identifierItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item.WithCustomer_identifierItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("customer_identifier", position);
                return new global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.Item.WithCustomer_identifierItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/alerts/mutes/{alert_mute_key}/customer", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V2.Alerts.Mutes.Item.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/alerts/mutes/{alert_mute_key}/customer", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
