// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment;
using PayNow.Libraries.ComplyAdvantageClient.V3.Transactions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.V3
{
    /// <summary>
    /// Builds and executes requests for operations under \v3
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V3RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The enrichment property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.EnrichmentRequestBuilder Enrichment
        {
            get => new global::PayNow.Libraries.ComplyAdvantageClient.V3.Enrichment.EnrichmentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.V3.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::PayNow.Libraries.ComplyAdvantageClient.V3.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.V3.V3RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V3RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
