// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Defines the type of card payment.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Activity_CardPaymentTypeV3
    {
        [EnumMember(Value = "REGULAR")]
        #pragma warning disable CS1591
        REGULAR,
        #pragma warning restore CS1591
        [EnumMember(Value = "INSTALLMENT")]
        #pragma warning disable CS1591
        INSTALLMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECURRING")]
        #pragma warning disable CS1591
        RECURRING,
        #pragma warning restore CS1591
        [EnumMember(Value = "MOTO")]
        #pragma warning disable CS1591
        MOTO,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSCHEDULED")]
        #pragma warning disable CS1591
        UNSCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOP_UP")]
        #pragma warning disable CS1591
        TOP_UP,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUND")]
        #pragma warning disable CS1591
        REFUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTH_ONLY")]
        #pragma warning disable CS1591
        AUTH_ONLY,
        #pragma warning restore CS1591
    }
}
