// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Represents the identification details of a party. This includes not just the party&apos;s identifier, but also any other identifying information specific to the transaction such as alternate names or addresses.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Activity_PartyIdentificationV3 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address? Address { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address Address { get; set; }
#endif
        /// <summary>The identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier? Identifier { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier Identifier { get; set; }
#endif
        /// <summary>The name of the party.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3"/> and sets the default values.
        /// </summary>
        public Activity_PartyIdentificationV3()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address.CreateFromDiscriminatorValue); } },
                { "identifier", n => { Identifier = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address>("address", Address);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier>("identifier", Identifier);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_StructuredAddressV3"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_UnstructuredAddressV3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Activity_PartyIdentificationV3_address : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_StructuredAddressV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_StructuredAddressV3? ActivityStructuredAddressV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_StructuredAddressV3 ActivityStructuredAddressV3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_UnstructuredAddressV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_UnstructuredAddressV3? ActivityUnstructuredAddressV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_UnstructuredAddressV3 ActivityUnstructuredAddressV3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("format")?.GetStringValue();
                var result = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_address();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityStructuredAddressV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_StructuredAddressV3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityUnstructuredAddressV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_UnstructuredAddressV3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActivityStructuredAddressV3 != null)
                {
                    return ActivityStructuredAddressV3.GetFieldDeserializers();
                }
                else if(ActivityUnstructuredAddressV3 != null)
                {
                    return ActivityUnstructuredAddressV3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ActivityStructuredAddressV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_StructuredAddressV3>(null, ActivityStructuredAddressV3);
                }
                else if(ActivityUnstructuredAddressV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_UnstructuredAddressV3>(null, ActivityUnstructuredAddressV3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CounterpartyPartyIdentifierV3"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CustomerPartyIdentifierV3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Activity_PartyIdentificationV3_identifier : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CounterpartyPartyIdentifierV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CounterpartyPartyIdentifierV3? ActivityCounterpartyPartyIdentifierV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CounterpartyPartyIdentifierV3 ActivityCounterpartyPartyIdentifierV3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CustomerPartyIdentifierV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CustomerPartyIdentifierV3? ActivityCustomerPartyIdentifierV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CustomerPartyIdentifierV3 ActivityCustomerPartyIdentifierV3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_PartyIdentificationV3.Activity_PartyIdentificationV3_identifier();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityCounterpartyPartyIdentifierV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CounterpartyPartyIdentifierV3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityCustomerPartyIdentifierV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CustomerPartyIdentifierV3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActivityCounterpartyPartyIdentifierV3 != null)
                {
                    return ActivityCounterpartyPartyIdentifierV3.GetFieldDeserializers();
                }
                else if(ActivityCustomerPartyIdentifierV3 != null)
                {
                    return ActivityCustomerPartyIdentifierV3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ActivityCounterpartyPartyIdentifierV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CounterpartyPartyIdentifierV3>(null, ActivityCounterpartyPartyIdentifierV3);
                }
                else if(ActivityCustomerPartyIdentifierV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Activity_CustomerPartyIdentifierV3>(null, ActivityCustomerPartyIdentifierV3);
                }
            }
        }
    }
}
#pragma warning restore CS0618
