// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Represents the states of review decision</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Activity_ReviewDecisionResponse_review_decision
    {
        [EnumMember(Value = "RELEASE")]
        #pragma warning disable CS1591
        RELEASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECT")]
        #pragma warning disable CS1591
        REJECT,
        #pragma warning restore CS1591
    }
}
