// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Represents the type of address.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddressTypeV3
    {
        [EnumMember(Value = "RESIDENTIAL")]
        #pragma warning disable CS1591
        RESIDENTIAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAILING")]
        #pragma warning disable CS1591
        MAILING,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPERATING")]
        #pragma warning disable CS1591
        OPERATING,
        #pragma warning restore CS1591
        [EnumMember(Value = "REGISTRATION")]
        #pragma warning disable CS1591
        REGISTRATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING")]
        #pragma warning disable CS1591
        BILLING,
        #pragma warning restore CS1591
    }
}
