// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Am_AlertMuteV3Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp when the alert mute was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Identifier of the user that created the alert mute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Entity scope the alert mute applies to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteEntityResponse? Entity { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteEntityResponse Entity { get; set; }
#endif
        /// <summary>Unique identifier of the alert mute.</summary>
        public Guid? Identifier { get; set; }
        /// <summary>Risk code/profile identifier muted for the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RiskCode { get; set; }
#nullable restore
#else
        public string RiskCode { get; set; }
#endif
        /// <summary>Risk signal identifier associated with the alert mute, when provided.</summary>
        public Guid? RiskSignalIdentifier { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteV3Response"/> and sets the default values.
        /// </summary>
        public Am_AlertMuteV3Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteV3Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteV3Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteV3Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetStringValue(); } },
                { "entity", n => { Entity = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteEntityResponse>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteEntityResponse.CreateFromDiscriminatorValue); } },
                { "identifier", n => { Identifier = n.GetGuidValue(); } },
                { "risk_code", n => { RiskCode = n.GetStringValue(); } },
                { "risk_signal_identifier", n => { RiskSignalIdentifier = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("created_by", CreatedBy);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Am_AlertMuteEntityResponse>("entity", Entity);
            writer.WriteGuidValue("identifier", Identifier);
            writer.WriteStringValue("risk_code", RiskCode);
            writer.WriteGuidValue("risk_signal_identifier", RiskSignalIdentifier);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
