// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Type of muted entity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Am_AlertMuteEntityResponse_type
    {
        [EnumMember(Value = "CUSTOMER")]
        #pragma warning disable CS1591
        CUSTOMER,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTERPARTY")]
        #pragma warning disable CS1591
        COUNTERPARTY,
        #pragma warning restore CS1591
    }
}
