// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Am_TransitionStatePayload_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSITIVE_END_STATE")]
        #pragma warning disable CS1591
        POSITIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEGATIVE_END_STATE")]
        #pragma warning disable CS1591
        NEGATIVE_END_STATE,
        #pragma warning restore CS1591
    }
}
