// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Audit_NoteToCustomerLogV2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NOTE_CREATED_TO_CUSTOMER")]
        #pragma warning disable CS1591
        NOTE_CREATED_TO_CUSTOMER,
        #pragma warning restore CS1591
    }
}
