// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Audit_TransactionAuditLogsPageV2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The audit_logs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs>? AuditLogs { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs> AuditLogs { get; set; }
#endif
        /// <summary>The URL path to the first page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? First { get; set; }
#nullable restore
#else
        public string First { get; set; }
#endif
        /// <summary>The URL path to the next page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Next { get; set; }
#nullable restore
#else
        public string Next { get; set; }
#endif
        /// <summary>The URL path to the previous page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prev { get; set; }
#nullable restore
#else
        public string Prev { get; set; }
#endif
        /// <summary>The URL path to the current page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Self { get; set; }
#nullable restore
#else
        public string Self { get; set; }
#endif
        /// <summary>Total number of items.</summary>
        public long? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2"/> and sets the default values.
        /// </summary>
        public Audit_TransactionAuditLogsPageV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audit_logs", n => { AuditLogs = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "first", n => { First = n.GetStringValue(); } },
                { "next", n => { Next = n.GetStringValue(); } },
                { "prev", n => { Prev = n.GetStringValue(); } },
                { "self", n => { Self = n.GetStringValue(); } },
                { "total_count", n => { TotalCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs>("audit_logs", AuditLogs);
            writer.WriteStringValue("first", First);
            writer.WriteStringValue("next", Next);
            writer.WriteStringValue("prev", Prev);
            writer.WriteStringValue("self", Self);
            writer.WriteLongValue("total_count", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseAssignedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_PaymentScreenedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAddedToCaseLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionMonitoredLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReceivedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReleaseDecisionLogV2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Audit_TransactionAuditLogsPageV2_audit_logs : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseAssignedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseAssignedLogV2? AuditCaseAssignedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseAssignedLogV2 AuditCaseAssignedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2? AuditCaseCreatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2 AuditCaseCreatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2? AuditCaseTransitionedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2 AuditCaseTransitionedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_PaymentScreenedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_PaymentScreenedLogV2? AuditPaymentScreenedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_PaymentScreenedLogV2 AuditPaymentScreenedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAddedToCaseLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAddedToCaseLogV2? AuditTransactionAddedToCaseLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAddedToCaseLogV2 AuditTransactionAddedToCaseLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionMonitoredLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionMonitoredLogV2? AuditTransactionMonitoredLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionMonitoredLogV2 AuditTransactionMonitoredLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReceivedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReceivedLogV2? AuditTransactionReceivedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReceivedLogV2 AuditTransactionReceivedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReleaseDecisionLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReleaseDecisionLogV2? AuditTransactionReleaseDecisionLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReleaseDecisionLogV2 AuditTransactionReleaseDecisionLogV2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAuditLogsPageV2.Audit_TransactionAuditLogsPageV2_audit_logs();
                if("CASE_ASSIGNED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCaseAssignedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseAssignedLogV2();
                }
                else if("CASE_CREATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCaseCreatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2();
                }
                else if("CASE_STAGE_TRANSITIONED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCaseTransitionedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2();
                }
                else if("PAYMENT_SCREENED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditPaymentScreenedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_PaymentScreenedLogV2();
                }
                else if("TRANSACTION_ADDED_TO_CASE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditTransactionAddedToCaseLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAddedToCaseLogV2();
                }
                else if("TRANSACTION_MONITORED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditTransactionMonitoredLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionMonitoredLogV2();
                }
                else if("TRANSACTION_RECEIVED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditTransactionReceivedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReceivedLogV2();
                }
                else if("TRANSACTION_RELEASE_DECISION".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditTransactionReleaseDecisionLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReleaseDecisionLogV2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AuditCaseAssignedLogV2 != null)
                {
                    return AuditCaseAssignedLogV2.GetFieldDeserializers();
                }
                else if(AuditCaseCreatedLogV2 != null)
                {
                    return AuditCaseCreatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCaseTransitionedLogV2 != null)
                {
                    return AuditCaseTransitionedLogV2.GetFieldDeserializers();
                }
                else if(AuditPaymentScreenedLogV2 != null)
                {
                    return AuditPaymentScreenedLogV2.GetFieldDeserializers();
                }
                else if(AuditTransactionAddedToCaseLogV2 != null)
                {
                    return AuditTransactionAddedToCaseLogV2.GetFieldDeserializers();
                }
                else if(AuditTransactionMonitoredLogV2 != null)
                {
                    return AuditTransactionMonitoredLogV2.GetFieldDeserializers();
                }
                else if(AuditTransactionReceivedLogV2 != null)
                {
                    return AuditTransactionReceivedLogV2.GetFieldDeserializers();
                }
                else if(AuditTransactionReleaseDecisionLogV2 != null)
                {
                    return AuditTransactionReleaseDecisionLogV2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(AuditCaseAssignedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseAssignedLogV2>(null, AuditCaseAssignedLogV2);
                }
                else if(AuditCaseCreatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2>(null, AuditCaseCreatedLogV2);
                }
                else if(AuditCaseTransitionedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2>(null, AuditCaseTransitionedLogV2);
                }
                else if(AuditPaymentScreenedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_PaymentScreenedLogV2>(null, AuditPaymentScreenedLogV2);
                }
                else if(AuditTransactionAddedToCaseLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionAddedToCaseLogV2>(null, AuditTransactionAddedToCaseLogV2);
                }
                else if(AuditTransactionMonitoredLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionMonitoredLogV2>(null, AuditTransactionMonitoredLogV2);
                }
                else if(AuditTransactionReceivedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReceivedLogV2>(null, AuditTransactionReceivedLogV2);
                }
                else if(AuditTransactionReleaseDecisionLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_TransactionReleaseDecisionLogV2>(null, AuditTransactionReleaseDecisionLogV2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
