// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Audit_CustomerWithStatus_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ONBOARDING")]
        #pragma warning disable CS1591
        ONBOARDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        ACTIVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOSED")]
        #pragma warning disable CS1591
        CLOSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING")]
        #pragma warning disable CS1591
        PROCESSING,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONBOARDING_CASE")]
        #pragma warning disable CS1591
        ONBOARDING_CASE,
        #pragma warning restore CS1591
    }
}
