// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Audit_AlertUnmutedForRiskLogV2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ALERT_UNMUTED_FOR_RISK")]
        #pragma warning disable CS1591
        ALERT_UNMUTED_FOR_RISK,
        #pragma warning restore CS1591
    }
}
