// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Audit_TransactionReceivedLogV2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TRANSACTION_RECEIVED")]
        #pragma warning disable CS1591
        TRANSACTION_RECEIVED,
        #pragma warning restore CS1591
    }
}
