// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Audit_CustomerAuditLogsPageV2 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The audit_logs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs>? AuditLogs { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs> AuditLogs { get; set; }
#endif
        /// <summary>The URL path to the first page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? First { get; set; }
#nullable restore
#else
        public string First { get; set; }
#endif
        /// <summary>The URL path to the next page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Next { get; set; }
#nullable restore
#else
        public string Next { get; set; }
#endif
        /// <summary>The URL path to the previous page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Prev { get; set; }
#nullable restore
#else
        public string Prev { get; set; }
#endif
        /// <summary>The URL path to the current page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Self { get; set; }
#nullable restore
#else
        public string Self { get; set; }
#endif
        /// <summary>Total number of items.</summary>
        public long? TotalCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2"/> and sets the default values.
        /// </summary>
        public Audit_CustomerAuditLogsPageV2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audit_logs", n => { AuditLogs = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "first", n => { First = n.GetStringValue(); } },
                { "next", n => { Next = n.GetStringValue(); } },
                { "prev", n => { Prev = n.GetStringValue(); } },
                { "self", n => { Self = n.GetStringValue(); } },
                { "total_count", n => { TotalCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs>("audit_logs", AuditLogs);
            writer.WriteStringValue("first", First);
            writer.WriteStringValue("next", Next);
            writer.WriteStringValue("prev", Prev);
            writer.WriteStringValue("self", Self);
            writer.WriteLongValue("total_count", TotalCount);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertMutedForRiskLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertUnmutedForRiskLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerCreatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerInfoUpdatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerLabelsUpdatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMigratedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMonitoringConfigurationUpdatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerProductUpdatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerScreenedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerSegmentsUpdatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerStatusUpdatedLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_NoteToCustomerLogV2"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_RiskScoreAssignedToCustomerLogV2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Audit_CustomerAuditLogsPageV2_audit_logs : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertMutedForRiskLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertMutedForRiskLogV2? AuditAlertMutedForRiskLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertMutedForRiskLogV2 AuditAlertMutedForRiskLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertUnmutedForRiskLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertUnmutedForRiskLogV2? AuditAlertUnmutedForRiskLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertUnmutedForRiskLogV2 AuditAlertUnmutedForRiskLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2? AuditCaseCreatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2 AuditCaseCreatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2? AuditCaseTransitionedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2 AuditCaseTransitionedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerCreatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerCreatedLogV2? AuditCustomerCreatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerCreatedLogV2 AuditCustomerCreatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerInfoUpdatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerInfoUpdatedLogV2? AuditCustomerInfoUpdatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerInfoUpdatedLogV2 AuditCustomerInfoUpdatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerLabelsUpdatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerLabelsUpdatedLogV2? AuditCustomerLabelsUpdatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerLabelsUpdatedLogV2 AuditCustomerLabelsUpdatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMigratedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMigratedLogV2? AuditCustomerMigratedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMigratedLogV2 AuditCustomerMigratedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMonitoringConfigurationUpdatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMonitoringConfigurationUpdatedLogV2? AuditCustomerMonitoringConfigurationUpdatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMonitoringConfigurationUpdatedLogV2 AuditCustomerMonitoringConfigurationUpdatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerProductUpdatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerProductUpdatedLogV2? AuditCustomerProductUpdatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerProductUpdatedLogV2 AuditCustomerProductUpdatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerScreenedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerScreenedLogV2? AuditCustomerScreenedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerScreenedLogV2 AuditCustomerScreenedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerSegmentsUpdatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerSegmentsUpdatedLogV2? AuditCustomerSegmentsUpdatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerSegmentsUpdatedLogV2 AuditCustomerSegmentsUpdatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerStatusUpdatedLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerStatusUpdatedLogV2? AuditCustomerStatusUpdatedLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerStatusUpdatedLogV2 AuditCustomerStatusUpdatedLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_NoteToCustomerLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_NoteToCustomerLogV2? AuditNoteToCustomerLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_NoteToCustomerLogV2 AuditNoteToCustomerLogV2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_RiskScoreAssignedToCustomerLogV2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_RiskScoreAssignedToCustomerLogV2? AuditRiskScoreAssignedToCustomerLogV2 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_RiskScoreAssignedToCustomerLogV2 AuditRiskScoreAssignedToCustomerLogV2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerAuditLogsPageV2.Audit_CustomerAuditLogsPageV2_audit_logs();
                if("ALERT_MUTED_FOR_RISK".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditAlertMutedForRiskLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertMutedForRiskLogV2();
                }
                else if("ALERT_UNMUTED_FOR_RISK".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditAlertUnmutedForRiskLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertUnmutedForRiskLogV2();
                }
                else if("CASE_CREATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCaseCreatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2();
                }
                else if("CASE_STAGE_TRANSITIONED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCaseTransitionedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2();
                }
                else if("CUSTOMER_CREATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerCreatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerCreatedLogV2();
                }
                else if("CUSTOMER_INFO_UPDATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerInfoUpdatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerInfoUpdatedLogV2();
                }
                else if("CUSTOMER_LABELS_UPDATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerLabelsUpdatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerLabelsUpdatedLogV2();
                }
                else if("CUSTOMER_MIGRATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerMigratedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMigratedLogV2();
                }
                else if("CUSTOMER_MONITORING_CONFIGURATION_UPDATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerMonitoringConfigurationUpdatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMonitoringConfigurationUpdatedLogV2();
                }
                else if("CUSTOMER_PRODUCT_UPDATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerProductUpdatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerProductUpdatedLogV2();
                }
                else if("CUSTOMER_SCREENED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerScreenedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerScreenedLogV2();
                }
                else if("CUSTOMER_SEGMENTS_UPDATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerSegmentsUpdatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerSegmentsUpdatedLogV2();
                }
                else if("CUSTOMER_STATUS_UPDATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditCustomerStatusUpdatedLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerStatusUpdatedLogV2();
                }
                else if("NOTE_CREATED_TO_CUSTOMER".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditNoteToCustomerLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_NoteToCustomerLogV2();
                }
                else if("RISK_SCORE_CALCULATED".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.AuditRiskScoreAssignedToCustomerLogV2 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_RiskScoreAssignedToCustomerLogV2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AuditAlertMutedForRiskLogV2 != null)
                {
                    return AuditAlertMutedForRiskLogV2.GetFieldDeserializers();
                }
                else if(AuditAlertUnmutedForRiskLogV2 != null)
                {
                    return AuditAlertUnmutedForRiskLogV2.GetFieldDeserializers();
                }
                else if(AuditCaseCreatedLogV2 != null)
                {
                    return AuditCaseCreatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCaseTransitionedLogV2 != null)
                {
                    return AuditCaseTransitionedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerCreatedLogV2 != null)
                {
                    return AuditCustomerCreatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerInfoUpdatedLogV2 != null)
                {
                    return AuditCustomerInfoUpdatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerLabelsUpdatedLogV2 != null)
                {
                    return AuditCustomerLabelsUpdatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerMigratedLogV2 != null)
                {
                    return AuditCustomerMigratedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerMonitoringConfigurationUpdatedLogV2 != null)
                {
                    return AuditCustomerMonitoringConfigurationUpdatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerProductUpdatedLogV2 != null)
                {
                    return AuditCustomerProductUpdatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerScreenedLogV2 != null)
                {
                    return AuditCustomerScreenedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerSegmentsUpdatedLogV2 != null)
                {
                    return AuditCustomerSegmentsUpdatedLogV2.GetFieldDeserializers();
                }
                else if(AuditCustomerStatusUpdatedLogV2 != null)
                {
                    return AuditCustomerStatusUpdatedLogV2.GetFieldDeserializers();
                }
                else if(AuditNoteToCustomerLogV2 != null)
                {
                    return AuditNoteToCustomerLogV2.GetFieldDeserializers();
                }
                else if(AuditRiskScoreAssignedToCustomerLogV2 != null)
                {
                    return AuditRiskScoreAssignedToCustomerLogV2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(AuditAlertMutedForRiskLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertMutedForRiskLogV2>(null, AuditAlertMutedForRiskLogV2);
                }
                else if(AuditAlertUnmutedForRiskLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_AlertUnmutedForRiskLogV2>(null, AuditAlertUnmutedForRiskLogV2);
                }
                else if(AuditCaseCreatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseCreatedLogV2>(null, AuditCaseCreatedLogV2);
                }
                else if(AuditCaseTransitionedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CaseTransitionedLogV2>(null, AuditCaseTransitionedLogV2);
                }
                else if(AuditCustomerCreatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerCreatedLogV2>(null, AuditCustomerCreatedLogV2);
                }
                else if(AuditCustomerInfoUpdatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerInfoUpdatedLogV2>(null, AuditCustomerInfoUpdatedLogV2);
                }
                else if(AuditCustomerLabelsUpdatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerLabelsUpdatedLogV2>(null, AuditCustomerLabelsUpdatedLogV2);
                }
                else if(AuditCustomerMigratedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMigratedLogV2>(null, AuditCustomerMigratedLogV2);
                }
                else if(AuditCustomerMonitoringConfigurationUpdatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerMonitoringConfigurationUpdatedLogV2>(null, AuditCustomerMonitoringConfigurationUpdatedLogV2);
                }
                else if(AuditCustomerProductUpdatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerProductUpdatedLogV2>(null, AuditCustomerProductUpdatedLogV2);
                }
                else if(AuditCustomerScreenedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerScreenedLogV2>(null, AuditCustomerScreenedLogV2);
                }
                else if(AuditCustomerSegmentsUpdatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerSegmentsUpdatedLogV2>(null, AuditCustomerSegmentsUpdatedLogV2);
                }
                else if(AuditCustomerStatusUpdatedLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_CustomerStatusUpdatedLogV2>(null, AuditCustomerStatusUpdatedLogV2);
                }
                else if(AuditNoteToCustomerLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_NoteToCustomerLogV2>(null, AuditNoteToCustomerLogV2);
                }
                else if(AuditRiskScoreAssignedToCustomerLogV2 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Audit_RiskScoreAssignedToCustomerLogV2>(null, AuditRiskScoreAssignedToCustomerLogV2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
