// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Defines the type of digital wallet.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardWalletTypeV3
    {
        [EnumMember(Value = "GOOGLE_PAY")]
        #pragma warning disable CS1591
        GOOGLE_PAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPLE_PAY")]
        #pragma warning disable CS1591
        APPLE_PAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYPAL")]
        #pragma warning disable CS1591
        PAYPAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "REMOTE_COMMERCE_PROGRAMS")]
        #pragma warning disable CS1591
        REMOTE_COMMERCE_PROGRAMS,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
