// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Represents the card scheme/network that issued the card.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardSchemeV3
    {
        [EnumMember(Value = "VISA")]
        #pragma warning disable CS1591
        VISA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MASTERCARD")]
        #pragma warning disable CS1591
        MASTERCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "AMERICAN_EXPRESS")]
        #pragma warning disable CS1591
        AMERICAN_EXPRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISCOVER")]
        #pragma warning disable CS1591
        DISCOVER,
        #pragma warning restore CS1591
        [EnumMember(Value = "JCB")]
        #pragma warning disable CS1591
        JCB,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNIONPAY")]
        #pragma warning disable CS1591
        UNIONPAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "DINERS_CLUB")]
        #pragma warning disable CS1591
        DINERS_CLUB,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAESTRO")]
        #pragma warning disable CS1591
        MAESTRO,
        #pragma warning restore CS1591
        [EnumMember(Value = "RUPAY")]
        #pragma warning disable CS1591
        RUPAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIR")]
        #pragma warning disable CS1591
        MIR,
        #pragma warning restore CS1591
    }
}
