// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>The current state of the case.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CaseManagement_CaseStatesResponse_name
    {
        [EnumMember(Value = "ONBOARDING_NOT_STARTED")]
        #pragma warning disable CS1591
        ONBOARDING_NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONBOARDING_IN_PROGRESS")]
        #pragma warning disable CS1591
        ONBOARDING_IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONBOARDING_POSITIVE_END_STATE")]
        #pragma warning disable CS1591
        ONBOARDING_POSITIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONBOARDING_MANAGEABLE_RISK_POSITIVE_END_STATE")]
        #pragma warning disable CS1591
        ONBOARDING_MANAGEABLE_RISK_POSITIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONBOARDING_NEGATIVE_END_STATE")]
        #pragma warning disable CS1591
        ONBOARDING_NEGATIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_NOT_STARTED")]
        #pragma warning disable CS1591
        MONITORING_NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_IN_PROGRESS")]
        #pragma warning disable CS1591
        MONITORING_IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_ESCALATED")]
        #pragma warning disable CS1591
        MONITORING_ESCALATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_BLOCKED")]
        #pragma warning disable CS1591
        MONITORING_BLOCKED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_NO_RISK_DETECTED_POSITIVE_END_STATE")]
        #pragma warning disable CS1591
        MONITORING_NO_RISK_DETECTED_POSITIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_RISK_DETECTED_POSITIVE_END_STATE")]
        #pragma warning disable CS1591
        MONITORING_RISK_DETECTED_POSITIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONITORING_RISK_DETECTED_NEGATIVE_END_STATE")]
        #pragma warning disable CS1591
        MONITORING_RISK_DETECTED_NEGATIVE_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_NOT_STARTED")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_IN_PROGRESS")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_ESCALATED")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_ESCALATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_BLOCKED")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_BLOCKED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_AWAITING_INFORMATION")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_AWAITING_INFORMATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_PROCESS_PAYMENT_END_STATE")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_PROCESS_PAYMENT_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_SCREENING_REJECT_PAYMENT_END_STATE")]
        #pragma warning disable CS1591
        PAYMENT_SCREENING_REJECT_PAYMENT_END_STATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_DEFINED")]
        #pragma warning disable CS1591
        USER_DEFINED,
        #pragma warning restore CS1591
    }
}
