// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Case transition response.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CaseManagement_CaseTransitionResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The stage identifier to which the case was last transitioned by a user.</summary>
        public Guid? LastUserStageIdentifier { get; set; }
        /// <summary>The last state the case was transitioned to by a user (as opposed to a system action).For those using the deprecated case_state, if any new case stages are added the case state response for these will be returned as  USER_DEFINED</summary>
        [Obsolete("")]
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse_last_user_state? LastUserState { get; set; }
        /// <summary>The stage identifier to which the case has been transitioned.</summary>
        public Guid? StageIdentifier { get; set; }
        /// <summary>The current state of the case.For those using the deprecated case_state, if any new case stages are added the case state response for these will be returned as USER_DEFINED</summary>
        [Obsolete("")]
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse_state? State { get; set; }
        /// <summary>The date and time at which this case was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The user identifier that last updated this case.</summary>
        public Guid? UpdatedBy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse"/> and sets the default values.
        /// </summary>
        public CaseManagement_CaseTransitionResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "last_user_stage_identifier", n => { LastUserStageIdentifier = n.GetGuidValue(); } },
                { "last_user_state", n => { LastUserState = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse_last_user_state>(); } },
                { "stage_identifier", n => { StageIdentifier = n.GetGuidValue(); } },
                { "state", n => { State = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse_state>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("last_user_stage_identifier", LastUserStageIdentifier);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse_last_user_state>("last_user_state", LastUserState);
            writer.WriteGuidValue("stage_identifier", StageIdentifier);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionResponse_state>("state", State);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteGuidValue("updated_by", UpdatedBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
