// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Note associated to a case state transition action.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CaseManagement_CaseTransitionNoteResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contents of the note.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Contents { get; set; }
#nullable restore
#else
        public string Contents { get; set; }
#endif
        /// <summary>The date and time at which this note was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The user identifier that created this note.</summary>
        public Guid? CreatedBy { get; set; }
        /// <summary>Unique identifier of the note.</summary>
        public Guid? Identifier { get; set; }
        /// <summary>Stage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_Stage? Stage { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_Stage Stage { get; set; }
#endif
        /// <summary>Available state to transition a case.</summary>
        [Obsolete("")]
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse_state? State { get; set; }
        /// <summary>Defines the type of a note.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse"/> and sets the default values.
        /// </summary>
        public CaseManagement_CaseTransitionNoteResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contents", n => { Contents = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetGuidValue(); } },
                { "identifier", n => { Identifier = n.GetGuidValue(); } },
                { "stage", n => { Stage = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_Stage>(global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_Stage.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse_state>(); } },
                { "type", n => { Type = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contents", Contents);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteGuidValue("created_by", CreatedBy);
            writer.WriteGuidValue("identifier", Identifier);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_Stage>("stage", Stage);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse_state>("state", State);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CaseTransitionNoteResponse_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
