// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_BankPaymentSummaryResponse"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CardPaymentSummaryResponse"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CryptoPaymentSummaryResponse"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_RemittancePaymentSummaryResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CaseManagement_PaymentSummaryResponse : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_BankPaymentSummaryResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_BankPaymentSummaryResponse? CaseManagementBankPaymentSummaryResponse { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_BankPaymentSummaryResponse CaseManagementBankPaymentSummaryResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CardPaymentSummaryResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CardPaymentSummaryResponse? CaseManagementCardPaymentSummaryResponse { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CardPaymentSummaryResponse CaseManagementCardPaymentSummaryResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CryptoPaymentSummaryResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CryptoPaymentSummaryResponse? CaseManagementCryptoPaymentSummaryResponse { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CryptoPaymentSummaryResponse CaseManagementCryptoPaymentSummaryResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_RemittancePaymentSummaryResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_RemittancePaymentSummaryResponse? CaseManagementRemittancePaymentSummaryResponse { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_RemittancePaymentSummaryResponse CaseManagementRemittancePaymentSummaryResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_PaymentSummaryResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_PaymentSummaryResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_PaymentSummaryResponse();
            if("case-management_BankPaymentSummaryResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CaseManagementBankPaymentSummaryResponse = new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_BankPaymentSummaryResponse();
            }
            else if("case-management_CardPaymentSummaryResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CaseManagementCardPaymentSummaryResponse = new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CardPaymentSummaryResponse();
            }
            else if("case-management_CryptoPaymentSummaryResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CaseManagementCryptoPaymentSummaryResponse = new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CryptoPaymentSummaryResponse();
            }
            else if("case-management_RemittancePaymentSummaryResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CaseManagementRemittancePaymentSummaryResponse = new global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_RemittancePaymentSummaryResponse();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CaseManagementBankPaymentSummaryResponse != null)
            {
                return CaseManagementBankPaymentSummaryResponse.GetFieldDeserializers();
            }
            else if(CaseManagementCardPaymentSummaryResponse != null)
            {
                return CaseManagementCardPaymentSummaryResponse.GetFieldDeserializers();
            }
            else if(CaseManagementCryptoPaymentSummaryResponse != null)
            {
                return CaseManagementCryptoPaymentSummaryResponse.GetFieldDeserializers();
            }
            else if(CaseManagementRemittancePaymentSummaryResponse != null)
            {
                return CaseManagementRemittancePaymentSummaryResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CaseManagementBankPaymentSummaryResponse != null)
            {
                writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_BankPaymentSummaryResponse>(null, CaseManagementBankPaymentSummaryResponse);
            }
            else if(CaseManagementCardPaymentSummaryResponse != null)
            {
                writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CardPaymentSummaryResponse>(null, CaseManagementCardPaymentSummaryResponse);
            }
            else if(CaseManagementCryptoPaymentSummaryResponse != null)
            {
                writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_CryptoPaymentSummaryResponse>(null, CaseManagementCryptoPaymentSummaryResponse);
            }
            else if(CaseManagementRemittancePaymentSummaryResponse != null)
            {
                writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CaseManagement_RemittancePaymentSummaryResponse>(null, CaseManagementRemittancePaymentSummaryResponse);
            }
        }
    }
}
#pragma warning restore CS0618
