// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Status of the report</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Cert_Report_status
    {
        [EnumMember(Value = "READY")]
        #pragma warning disable CS1591
        READY,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_READY")]
        #pragma warning disable CS1591
        NOT_READY,
        #pragma warning restore CS1591
    }
}
