// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Customlist_PersonAddDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_AddressDTO>? Addresses { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_AddressDTO> Addresses { get; set; }
#endif
        /// <summary>Date in the format YYYY-MM-DD. Expected to be in the past and later than 1800-01-01</summary>
        public Date? DateOfBirth { get; set; }
        /// <summary>The identifiers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_IdentifierDTO>? Identifiers { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_IdentifierDTO> Identifiers { get; set; }
#endif
        /// <summary>The names property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonNamesDTO? Names { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonNamesDTO Names { get; set; }
#endif
        /// <summary>2 letter country code as defined by iso-3166-alpha-2</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Nationalities { get; set; }
#nullable restore
#else
        public List<string> Nationalities { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonAddDTO"/> and sets the default values.
        /// </summary>
        public Customlist_PersonAddDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonAddDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonAddDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonAddDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addresses", n => { Addresses = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_AddressDTO>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_AddressDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "date_of_birth", n => { DateOfBirth = n.GetDateValue(); } },
                { "identifiers", n => { Identifiers = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_IdentifierDTO>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_IdentifierDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "names", n => { Names = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonNamesDTO>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonNamesDTO.CreateFromDiscriminatorValue); } },
                { "nationalities", n => { Nationalities = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_AddressDTO>("addresses", Addresses);
            writer.WriteDateValue("date_of_birth", DateOfBirth);
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_IdentifierDTO>("identifiers", Identifiers);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Customlist_PersonNamesDTO>("names", Names);
            writer.WriteCollectionOfPrimitiveValues<string>("nationalities", Nationalities);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
