// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CustomerManager_CreateCustomerNoteResponse_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CUSTOMER")]
        #pragma warning disable CS1591
        CUSTOMER,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_MONITORING")]
        #pragma warning disable CS1591
        CUSTOMER_MONITORING,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_STATUS")]
        #pragma warning disable CS1591
        CUSTOMER_STATUS,
        #pragma warning restore CS1591
    }
}
