// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerManager_CustomerForSearch : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acquisition_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcquisitionSource { get; set; }
#nullable restore
#else
        public string AcquisitionSource { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CompanyForSearch? Company { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CompanyForSearch Company { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The customer_identifier property</summary>
        public Guid? CustomerIdentifier { get; set; }
        /// <summary>The external_identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalIdentifier { get; set; }
#nullable restore
#else
        public string ExternalIdentifier { get; set; }
#endif
        /// <summary>The monitor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_MonitorStatus? Monitor { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_MonitorStatus Monitor { get; set; }
#endif
        /// <summary>The person property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_PersonForSearch? Person { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_PersonForSearch Person { get; set; }
#endif
        /// <summary>The scores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_RiskScore? Scores { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_RiskScore Scores { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch_status? Status { get; set; }
        /// <summary>The undefined_customer_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_UndefinedForSearch? UndefinedCustomerType { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_UndefinedForSearch UndefinedCustomerType { get; set; }
#endif
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch"/> and sets the default values.
        /// </summary>
        public CustomerManager_CustomerForSearch()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acquisition_source", n => { AcquisitionSource = n.GetStringValue(); } },
                { "company", n => { Company = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CompanyForSearch>(global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CompanyForSearch.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customer_identifier", n => { CustomerIdentifier = n.GetGuidValue(); } },
                { "external_identifier", n => { ExternalIdentifier = n.GetStringValue(); } },
                { "monitor", n => { Monitor = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_MonitorStatus>(global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_MonitorStatus.CreateFromDiscriminatorValue); } },
                { "person", n => { Person = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_PersonForSearch>(global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_PersonForSearch.CreateFromDiscriminatorValue); } },
                { "scores", n => { Scores = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_RiskScore>(global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_RiskScore.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch_status>(); } },
                { "undefined_customer_type", n => { UndefinedCustomerType = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_UndefinedForSearch>(global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_UndefinedForSearch.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acquisition_source", AcquisitionSource);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CompanyForSearch>("company", Company);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteGuidValue("customer_identifier", CustomerIdentifier);
            writer.WriteStringValue("external_identifier", ExternalIdentifier);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_MonitorStatus>("monitor", Monitor);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_PersonForSearch>("person", Person);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_RiskScore>("scores", Scores);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_CustomerForSearch_status>("status", Status);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.CustomerManager_UndefinedForSearch>("undefined_customer_type", UndefinedCustomerType);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
