// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>The type of enrichment source.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnrichmentTypeV3
    {
        [EnumMember(Value = "LOOKUP_LIST")]
        #pragma warning disable CS1591
        LOOKUP_LIST,
        #pragma warning restore CS1591
    }
}
