// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// List of accounts.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExtendedUserAccountsRoles : IAdditionalDataHolder, IParsable
    {
        /// <summary>Type of the account.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles_account_type? AccountType { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the client.</summary>
        public Guid? ClientIdentifier { get; set; }
        /// <summary>The unique identifier of the account.</summary>
        public Guid? Identifier { get; set; }
        /// <summary>Name of the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>List of roles within the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserRole>? Roles { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserRole> Roles { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles"/> and sets the default values.
        /// </summary>
        public ExtendedUserAccountsRoles()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_type", n => { AccountType = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles_account_type>(); } },
                { "client_identifier", n => { ClientIdentifier = n.GetGuidValue(); } },
                { "identifier", n => { Identifier = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserRole>(global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserRole.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserAccountsRoles_account_type>("account_type", AccountType);
            writer.WriteGuidValue("client_identifier", ClientIdentifier);
            writer.WriteGuidValue("identifier", Identifier);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.ExtendedUserRole>("roles", Roles);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
