// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// List of users.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Identity_NoRolesUserData : IAdditionalDataHolder, IParsable
    {
        /// <summary>If a user is active or deactivated.</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the client.</summary>
        public Guid? ClientIdentifier { get; set; }
        /// <summary>Date and time the user was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The unique identifier of who created the user.</summary>
        public Guid? CreatedBy { get; set; }
        /// <summary>Date and time the user was deactivated.</summary>
        public DateTimeOffset? DeactivatedAt { get; set; }
        /// <summary>Email address of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Date and time of when MFA will be enforced for the user.</summary>
        public DateTimeOffset? EnforceMfaAfter { get; set; }
        /// <summary>The unique identifier of the user.</summary>
        public Guid? Identifier { get; set; }
        /// <summary>Full name of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Date and time the user was last updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The unique identifier of who last updated the user.</summary>
        public Guid? UpdatedBy { get; set; }
        /// <summary>The user_type property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData_user_type? UserType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData"/> and sets the default values.
        /// </summary>
        public Identity_NoRolesUserData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "client_identifier", n => { ClientIdentifier = n.GetGuidValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetGuidValue(); } },
                { "deactivated_at", n => { DeactivatedAt = n.GetDateTimeOffsetValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "enforce_mfa_after", n => { EnforceMfaAfter = n.GetDateTimeOffsetValue(); } },
                { "identifier", n => { Identifier = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetGuidValue(); } },
                { "user_type", n => { UserType = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData_user_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteGuidValue("client_identifier", ClientIdentifier);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteGuidValue("created_by", CreatedBy);
            writer.WriteDateTimeOffsetValue("deactivated_at", DeactivatedAt);
            writer.WriteStringValue("email", Email);
            writer.WriteDateTimeOffsetValue("enforce_mfa_after", EnforceMfaAfter);
            writer.WriteGuidValue("identifier", Identifier);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteGuidValue("updated_by", UpdatedBy);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Identity_NoRolesUserData_user_type>("user_type", UserType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
