// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Represents the category types for Merchant Category Codes based on industry code ranges.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MerchantV3_category_type
    {
        [EnumMember(Value = "AGRICULTURAL_SERVICES")]
        #pragma warning disable CS1591
        AGRICULTURAL_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTRACTED_SERVICES")]
        #pragma warning disable CS1591
        CONTRACTED_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSPORTATION_SERVICES")]
        #pragma warning disable CS1591
        TRANSPORTATION_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "UTILITY_SERVICES")]
        #pragma warning disable CS1591
        UTILITY_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "RETAIL_OUTLET_SERVICES")]
        #pragma warning disable CS1591
        RETAIL_OUTLET_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "CLOTHING_SHOPS")]
        #pragma warning disable CS1591
        CLOTHING_SHOPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISCELLANEOUS_SHOPS")]
        #pragma warning disable CS1591
        MISCELLANEOUS_SHOPS,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUSINESS_SERVICES")]
        #pragma warning disable CS1591
        BUSINESS_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROFESSIONAL_SERVICES")]
        #pragma warning disable CS1591
        PROFESSIONAL_SERVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "GOVERNMENT_SERVICES")]
        #pragma warning disable CS1591
        GOVERNMENT_SERVICES,
        #pragma warning restore CS1591
    }
}
