// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Ol_Address_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "RESIDENTIAL_ADDRESS")]
        #pragma warning disable CS1591
        RESIDENTIAL_ADDRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAILING_ADDRESS")]
        #pragma warning disable CS1591
        MAILING_ADDRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPERATING_ADDRESS")]
        #pragma warning disable CS1591
        OPERATING_ADDRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "REGISTRATION_ADDRESS")]
        #pragma warning disable CS1591
        REGISTRATION_ADDRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING_ADDRESS")]
        #pragma warning disable CS1591
        BILLING_ADDRESS,
        #pragma warning restore CS1591
    }
}
