// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Models a transfer of funds from one bank account to another in a different financial institution.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ol_BankPaymentMonetaryTransactionTypeDetailsV3 : global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MonetaryTransactionTypeDetailsV3, IParsable
    {
        /// <summary>Any intermediaries involved in the transaction between the creditor and the debtor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AgentV3>? Agents { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AgentV3> Agents { get; set; }
#endif
        /// <summary>Represents the identification details of a party. This includes not just the party&apos;s identifier, but also any other identifying information specific to the transaction such as alternate names or addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3? Creditor { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3 Creditor { get; set; }
#endif
        /// <summary>Represents the identification details of a party. This includes not just the party&apos;s identifier, but also any other identifying information specific to the transaction such as alternate names or addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3? Debtor { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3 Debtor { get; set; }
#endif
        /// <summary>The payment scheme that was used to initiate the financial transaction.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentSchemeV3? PaymentScheme { get; set; }
        /// <summary>The possible states of a bank payment transaction.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BankPaymentStateV3? State { get; set; }
        /// <summary>Represents the identification details of a party. This includes not just the party&apos;s identifier, but also any other identifying information specific to the transaction such as alternate names or addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3? UltimateCreditor { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3 UltimateCreditor { get; set; }
#endif
        /// <summary>Represents the identification details of a party. This includes not just the party&apos;s identifier, but also any other identifying information specific to the transaction such as alternate names or addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3? UltimateDebtor { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3 UltimateDebtor { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BankPaymentMonetaryTransactionTypeDetailsV3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BankPaymentMonetaryTransactionTypeDetailsV3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BankPaymentMonetaryTransactionTypeDetailsV3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "agents", n => { Agents = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AgentV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AgentV3.CreateFromDiscriminatorValue)?.AsList(); } },
                { "creditor", n => { Creditor = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3.CreateFromDiscriminatorValue); } },
                { "debtor", n => { Debtor = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3.CreateFromDiscriminatorValue); } },
                { "payment_scheme", n => { PaymentScheme = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentSchemeV3>(); } },
                { "state", n => { State = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BankPaymentStateV3>(); } },
                { "ultimate_creditor", n => { UltimateCreditor = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3.CreateFromDiscriminatorValue); } },
                { "ultimate_debtor", n => { UltimateDebtor = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AgentV3>("agents", Agents);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>("creditor", Creditor);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>("debtor", Debtor);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentSchemeV3>("payment_scheme", PaymentScheme);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BankPaymentStateV3>("state", State);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>("ultimate_creditor", UltimateCreditor);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PartyIdentificationV3>("ultimate_debtor", UltimateDebtor);
        }
    }
}
#pragma warning restore CS0618
