// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Customer to be created and screened. It can be either a person, a company or undefined.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ol_CustomerApi : IAdditionalDataHolder, IParsable
    {
        /// <summary>The acquisition_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AcquisitionSource { get; set; }
#nullable restore
#else
        public string AcquisitionSource { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Company? Company { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Company Company { get; set; }
#endif
        /// <summary>The customer_since property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Date? CustomerSince { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Date CustomerSince { get; set; }
#endif
        /// <summary>The external_identifier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalIdentifier { get; set; }
#nullable restore
#else
        public string ExternalIdentifier { get; set; }
#endif
        /// <summary>The person property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Person? Person { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Person Person { get; set; }
#endif
        /// <summary>The undefined property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerTypeUndefined? Undefined { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerTypeUndefined Undefined { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerApi"/> and sets the default values.
        /// </summary>
        public Ol_CustomerApi()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerApi"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerApi CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerApi();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acquisition_source", n => { AcquisitionSource = n.GetStringValue(); } },
                { "company", n => { Company = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Company>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Company.CreateFromDiscriminatorValue); } },
                { "customer_since", n => { CustomerSince = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Date>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Date.CreateFromDiscriminatorValue); } },
                { "external_identifier", n => { ExternalIdentifier = n.GetStringValue(); } },
                { "person", n => { Person = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Person>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Person.CreateFromDiscriminatorValue); } },
                { "undefined", n => { Undefined = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerTypeUndefined>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerTypeUndefined.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("acquisition_source", AcquisitionSource);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Company>("company", Company);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Date>("customer_since", CustomerSince);
            writer.WriteStringValue("external_identifier", ExternalIdentifier);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_Person>("person", Person);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CustomerTypeUndefined>("undefined", Undefined);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
