// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// Models a card payment transaction where funds are transferred using a payment card.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ol_CardPaymentMonetaryTransactionTypeDetailsV3 : global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MonetaryTransactionTypeDetailsV3, IParsable
    {
        /// <summary>Represents the payment acquirer information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AcquirerV3? Acquirer { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AcquirerV3 Acquirer { get; set; }
#endif
        /// <summary>Details about a payment card used in a transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentCardV3? Card { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentCardV3 Card { get; set; }
#endif
        /// <summary>Represents a card holder with party identification details and onboarding information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardHolderV3? CardHolder { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardHolderV3 CardHolder { get; set; }
#endif
        /// <summary>Defines the scope of a card payment transaction.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentScopeV3? CardPaymentScope { get; set; }
        /// <summary>Defines the type of card payment.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentTypeV3? CardPaymentType { get; set; }
        /// <summary>Represents the card scheme/network that issued the card.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardSchemeV3? CardScheme { get; set; }
        /// <summary>Represents card verification results including CVV, AVS, and identity checks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardVerificationResultsV3? CardVerificationResults { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardVerificationResultsV3 CardVerificationResults { get; set; }
#endif
        /// <summary>Represents the card issuer information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_IssuerV3? Issuer { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_IssuerV3 Issuer { get; set; }
#endif
        /// <summary>Represents merchant information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3? Merchant { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3 Merchant { get; set; }
#endif
        /// <summary>Defines the stage of a card payment transaction.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentStageV3? PaymentStage { get; set; }
        /// <summary>Payment stages information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentStagesInfoV3? PaymentStagesInfo { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentStagesInfoV3 PaymentStagesInfo { get; set; }
#endif
        /// <summary>Contains contextual information about the card payment environment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PointOfSaleConditionV3? PointOfSale { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PointOfSaleConditionV3 PointOfSale { get; set; }
#endif
        /// <summary>Reference ID linking to parent/related transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RelatedTransactionIdentifier { get; set; }
#nullable restore
#else
        public string RelatedTransactionIdentifier { get; set; }
#endif
        /// <summary>Represents merchant information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3? SubMerchant { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3 SubMerchant { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentMonetaryTransactionTypeDetailsV3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentMonetaryTransactionTypeDetailsV3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentMonetaryTransactionTypeDetailsV3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "acquirer", n => { Acquirer = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AcquirerV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AcquirerV3.CreateFromDiscriminatorValue); } },
                { "card", n => { Card = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentCardV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentCardV3.CreateFromDiscriminatorValue); } },
                { "card_holder", n => { CardHolder = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardHolderV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardHolderV3.CreateFromDiscriminatorValue); } },
                { "card_payment_scope", n => { CardPaymentScope = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentScopeV3>(); } },
                { "card_payment_type", n => { CardPaymentType = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentTypeV3>(); } },
                { "card_scheme", n => { CardScheme = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardSchemeV3>(); } },
                { "card_verification_results", n => { CardVerificationResults = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardVerificationResultsV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardVerificationResultsV3.CreateFromDiscriminatorValue); } },
                { "issuer", n => { Issuer = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_IssuerV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_IssuerV3.CreateFromDiscriminatorValue); } },
                { "merchant", n => { Merchant = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3.CreateFromDiscriminatorValue); } },
                { "payment_stage", n => { PaymentStage = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentStageV3>(); } },
                { "payment_stages_info", n => { PaymentStagesInfo = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentStagesInfoV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentStagesInfoV3.CreateFromDiscriminatorValue); } },
                { "point_of_sale", n => { PointOfSale = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PointOfSaleConditionV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PointOfSaleConditionV3.CreateFromDiscriminatorValue); } },
                { "related_transaction_identifier", n => { RelatedTransactionIdentifier = n.GetStringValue(); } },
                { "sub_merchant", n => { SubMerchant = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_AcquirerV3>("acquirer", Acquirer);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentCardV3>("card", Card);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardHolderV3>("card_holder", CardHolder);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentScopeV3>("card_payment_scope", CardPaymentScope);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentTypeV3>("card_payment_type", CardPaymentType);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardSchemeV3>("card_scheme", CardScheme);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardVerificationResultsV3>("card_verification_results", CardVerificationResults);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_IssuerV3>("issuer", Issuer);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3>("merchant", Merchant);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CardPaymentStageV3>("payment_stage", PaymentStage);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PaymentStagesInfoV3>("payment_stages_info", PaymentStagesInfo);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_PointOfSaleConditionV3>("point_of_sale", PointOfSale);
            writer.WriteStringValue("related_transaction_identifier", RelatedTransactionIdentifier);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_MerchantV3>("sub_merchant", SubMerchant);
        }
    }
}
#pragma warning restore CS0618
