// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Ol_CreateAndProcessTransactionDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The list of scenario configurations the transaction should be monitored against.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? ScenarioConfigurationIdentifiers { get; set; }
#nullable restore
#else
        public List<Guid?> ScenarioConfigurationIdentifiers { get; set; }
#endif
        /// <summary>The configuration identifier to be used to screening the transaction.</summary>
        public Guid? ScreeningConfigurationIdentifier { get; set; }
        /// <summary>Represents a Transaction performed by a Customer. A Transaction can be either monetary or non-monetary.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionV3? Transaction { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionV3 Transaction { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CreateAndProcessTransactionDTO"/> and sets the default values.
        /// </summary>
        public Ol_CreateAndProcessTransactionDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CreateAndProcessTransactionDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CreateAndProcessTransactionDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_CreateAndProcessTransactionDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "scenario_configuration_identifiers", n => { ScenarioConfigurationIdentifiers = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "screening_configuration_identifier", n => { ScreeningConfigurationIdentifier = n.GetGuidValue(); } },
                { "transaction", n => { Transaction = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionV3>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionV3.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<Guid?>("scenario_configuration_identifiers", ScenarioConfigurationIdentifiers);
            writer.WriteGuidValue("screening_configuration_identifier", ScreeningConfigurationIdentifier);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionV3>("transaction", Transaction);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
