// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// A representation of a transaction enrichment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Ol_EnrichmentV3 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The key of the enrichment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The type of enrichment source.</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentTypeV3? Type { get; set; }
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value? Value { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3"/> and sets the default values.
        /// </summary>
        public Ol_EnrichmentV3()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "key", n => { Key = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentTypeV3>(); } },
                { "value", n => { Value = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("key", Key);
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentTypeV3>("type", Type);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BooleanEnrichmentValueV3"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_DecimalEnrichmentValueV3"/>, <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TextEnrichmentValueV3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Ol_EnrichmentV3_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BooleanEnrichmentValueV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BooleanEnrichmentValueV3? OlBooleanEnrichmentValueV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BooleanEnrichmentValueV3 OlBooleanEnrichmentValueV3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_DecimalEnrichmentValueV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_DecimalEnrichmentValueV3? OlDecimalEnrichmentValueV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_DecimalEnrichmentValueV3 OlDecimalEnrichmentValueV3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TextEnrichmentValueV3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TextEnrichmentValueV3? OlTextEnrichmentValueV3 { get; set; }
#nullable restore
#else
            public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TextEnrichmentValueV3 OlTextEnrichmentValueV3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("data_type")?.GetStringValue();
                var result = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EnrichmentV3.Ol_EnrichmentV3_value();
                if("BOOLEAN".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.OlBooleanEnrichmentValueV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BooleanEnrichmentValueV3();
                }
                else if("DECIMAL".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.OlDecimalEnrichmentValueV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_DecimalEnrichmentValueV3();
                }
                else if("TEXT".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.OlTextEnrichmentValueV3 = new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TextEnrichmentValueV3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OlBooleanEnrichmentValueV3 != null)
                {
                    return OlBooleanEnrichmentValueV3.GetFieldDeserializers();
                }
                else if(OlDecimalEnrichmentValueV3 != null)
                {
                    return OlDecimalEnrichmentValueV3.GetFieldDeserializers();
                }
                else if(OlTextEnrichmentValueV3 != null)
                {
                    return OlTextEnrichmentValueV3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(OlBooleanEnrichmentValueV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_BooleanEnrichmentValueV3>(null, OlBooleanEnrichmentValueV3);
                }
                else if(OlDecimalEnrichmentValueV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_DecimalEnrichmentValueV3>(null, OlDecimalEnrichmentValueV3);
                }
                else if(OlTextEnrichmentValueV3 != null)
                {
                    writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TextEnrichmentValueV3>(null, OlTextEnrichmentValueV3);
                }
            }
        }
    }
}
#pragma warning restore CS0618
