// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>The delivery method. Currently only `WEBHOOK` is supported.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ol_EvaluationResultDeliveryDTO_method
    {
        [EnumMember(Value = "WEBHOOK")]
        #pragma warning disable CS1591
        WEBHOOK,
        #pragma warning restore CS1591
    }
}
