// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Ol_EvaluationResultDTO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The outcome property</summary>
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO_outcome? Outcome { get; set; }
        /// <summary>The scenario_evaluations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ScenarioConfigurationEvaluationDTO>? ScenarioEvaluations { get; set; }
#nullable restore
#else
        public List<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ScenarioConfigurationEvaluationDTO> ScenarioEvaluations { get; set; }
#endif
        /// <summary>The screening_evaluation_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionScreeningEvaluationDTO? ScreeningEvaluationResults { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionScreeningEvaluationDTO ScreeningEvaluationResults { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO"/> and sets the default values.
        /// </summary>
        public Ol_EvaluationResultDTO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "outcome", n => { Outcome = n.GetEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO_outcome>(); } },
                { "scenario_evaluations", n => { ScenarioEvaluations = n.GetCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ScenarioConfigurationEvaluationDTO>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ScenarioConfigurationEvaluationDTO.CreateFromDiscriminatorValue)?.AsList(); } },
                { "screening_evaluation_results", n => { ScreeningEvaluationResults = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionScreeningEvaluationDTO>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionScreeningEvaluationDTO.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_EvaluationResultDTO_outcome>("outcome", Outcome);
            writer.WriteCollectionOfObjectValues<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_ScenarioConfigurationEvaluationDTO>("scenario_evaluations", ScenarioEvaluations);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Ol_TransactionScreeningEvaluationDTO>("screening_evaluation_results", ScreeningEvaluationResults);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
