// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Ol_EvaluationResultDeliveryDTO_method
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "WEBHOOK")]
        #pragma warning disable CS1591
        WEBHOOK,
        #pragma warning restore CS1591
    }
}
