// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Defines the subtype of FinCEN transactions.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ol_FincenCashTransactionSubtype
    {
        [EnumMember(Value = "DEPOSIT")]
        #pragma warning disable CS1591
        DEPOSIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT")]
        #pragma warning disable CS1591
        PAYMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURRENCY_TRANSFER_OUT")]
        #pragma warning disable CS1591
        CURRENCY_TRANSFER_OUT,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEGOTIABLE_INSTRUMENT_PURCHASE")]
        #pragma warning disable CS1591
        NEGOTIABLE_INSTRUMENT_PURCHASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURRENCY_EXCHANGE")]
        #pragma warning disable CS1591
        CURRENCY_EXCHANGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURRENCY_TO_PREPAID_ACCESS")]
        #pragma warning disable CS1591
        CURRENCY_TO_PREPAID_ACCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMING_INSTRUMENT_PURCHASE")]
        #pragma warning disable CS1591
        GAMING_INSTRUMENT_PURCHASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURRENCY_WAGER")]
        #pragma warning disable CS1591
        CURRENCY_WAGER,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLS_INSERTED_INTO_GAMING_DEVICES")]
        #pragma warning disable CS1591
        BILLS_INSERTED_INTO_GAMING_DEVICES,
        #pragma warning restore CS1591
        [EnumMember(Value = "WITHDRAWAL")]
        #pragma warning disable CS1591
        WITHDRAWAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADVANCE_ON_CREDIT")]
        #pragma warning disable CS1591
        ADVANCE_ON_CREDIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURRENCY_TRANSFER_IN")]
        #pragma warning disable CS1591
        CURRENCY_TRANSFER_IN,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEGOTIABLE_INSTRUMENT_CASHED")]
        #pragma warning disable CS1591
        NEGOTIABLE_INSTRUMENT_CASHED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CURRENCY_FROM_PREPAID_ACCESS")]
        #pragma warning disable CS1591
        CURRENCY_FROM_PREPAID_ACCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "GAMING_INSTRUMENT_REDEMPTION")]
        #pragma warning disable CS1591
        GAMING_INSTRUMENT_REDEMPTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_ON_WAGER")]
        #pragma warning disable CS1591
        PAYMENT_ON_WAGER,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAVEL_COMPLIMENTARY_EXPENSES")]
        #pragma warning disable CS1591
        TRAVEL_COMPLIMENTARY_EXPENSES,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROMOTION_PAYMENT")]
        #pragma warning disable CS1591
        PROMOTION_PAYMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
