// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Ol_TransactionScreeningEvaluationDTO_outcome
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESS")]
        #pragma warning disable CS1591
        PROCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "HOLD")]
        #pragma warning disable CS1591
        HOLD,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECT")]
        #pragma warning disable CS1591
        REJECT,
        #pragma warning restore CS1591
    }
}
