// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Ol_WorkflowState_workflow_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "create-and-screen")]
        #pragma warning disable CS1591
        CreateAndScreen,
        #pragma warning restore CS1591
        [EnumMember(Value = "update-and-rescore")]
        #pragma warning disable CS1591
        UpdateAndRescore,
        #pragma warning restore CS1591
        [EnumMember(Value = "rescreen-customer")]
        #pragma warning disable CS1591
        RescreenCustomer,
        #pragma warning restore CS1591
    }
}
