// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Choose how strict you want the BIC search to be. BANK is the least strict, returning a match for any BIC matching the first 4 digits, COUNTRY returns a match on the first 6 digits, LOCATION returns a match on the first 8 digits, and BRANCH requires a match on 11 digits. If not supplied, the default is full match on the BIC, whether length is 8 or 11 digits.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ps_BicSettings_strictness
    {
        [EnumMember(Value = "BANK")]
        #pragma warning disable CS1591
        BANK,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTRY")]
        #pragma warning disable CS1591
        COUNTRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOCATION")]
        #pragma warning disable CS1591
        LOCATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "BRANCH")]
        #pragma warning disable CS1591
        BRANCH,
        #pragma warning restore CS1591
    }
}
