// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>The type of sources in this collection. CUSTOM_LIST collections may only be used with name_screening_settings.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Ps_SourceCollection_source_type
    {
        [EnumMember(Value = "SANCTION")]
        #pragma warning disable CS1591
        SANCTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOM_LIST")]
        #pragma warning disable CS1591
        CUSTOM_LIST,
        #pragma warning restore CS1591
    }
}
