// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>TIN type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Reg_TinWithUnknown_type
    {
        [EnumMember(Value = "UNKNOWN_TIN")]
        #pragma warning disable CS1591
        UNKNOWN_TIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "EIN")]
        #pragma warning disable CS1591
        EIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "SSN_ITIN")]
        #pragma warning disable CS1591
        SSN_ITIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "FOREIGN_TIN")]
        #pragma warning disable CS1591
        FOREIGN_TIN,
        #pragma warning restore CS1591
    }
}
