// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Identification type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Reg_SarInstitutionIdentification_type
    {
        [EnumMember(Value = "CRD")]
        #pragma warning disable CS1591
        CRD,
        #pragma warning restore CS1591
        [EnumMember(Value = "IARD")]
        #pragma warning disable CS1591
        IARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAIC")]
        #pragma warning disable CS1591
        NAIC,
        #pragma warning restore CS1591
        [EnumMember(Value = "NFA")]
        #pragma warning disable CS1591
        NFA,
        #pragma warning restore CS1591
        [EnumMember(Value = "NMLS")]
        #pragma warning disable CS1591
        NMLS,
        #pragma warning restore CS1591
        [EnumMember(Value = "RSSD")]
        #pragma warning disable CS1591
        RSSD,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEC")]
        #pragma warning disable CS1591
        SEC,
        #pragma warning restore CS1591
    }
}
