// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>The relationship between the sender and receiver in a remittance transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RemittanceRelationshipV3
    {
        [EnumMember(Value = "SPOUSE")]
        #pragma warning disable CS1591
        SPOUSE,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAMILY")]
        #pragma warning disable CS1591
        FAMILY,
        #pragma warning restore CS1591
        [EnumMember(Value = "FRIEND")]
        #pragma warning disable CS1591
        FRIEND,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUSINESS_PARTNER")]
        #pragma warning disable CS1591
        BUSINESS_PARTNER,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMPLOYEE")]
        #pragma warning disable CS1591
        EMPLOYEE,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
    }
}
