// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RiskScoring_CategoryResult_category
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "BASIC_INFORMATION")]
        #pragma warning disable CS1591
        BASIC_INFORMATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHANNEL")]
        #pragma warning disable CS1591
        CHANNEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTRY")]
        #pragma warning disable CS1591
        COUNTRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRODUCT")]
        #pragma warning disable CS1591
        PRODUCT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCREENING")]
        #pragma warning disable CS1591
        SCREENING,
        #pragma warning restore CS1591
    }
}
