// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Defines the stage of a card payment transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Search_CardPaymentStageV3
    {
        [EnumMember(Value = "AUTHORIZED")]
        #pragma warning disable CS1591
        AUTHORIZED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SETTLED")]
        #pragma warning disable CS1591
        SETTLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVERSED")]
        #pragma warning disable CS1591
        REVERSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIALLY_SETTLED")]
        #pragma warning disable CS1591
        PARTIALLY_SETTLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHARGEBACK")]
        #pragma warning disable CS1591
        CHARGEBACK,
        #pragma warning restore CS1591
    }
}
