// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Type of risk</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Sra_Risk_type
    {
        [EnumMember(Value = "ENTITY_SCREENING")]
        #pragma warning disable CS1591
        ENTITY_SCREENING,
        #pragma warning restore CS1591
    }
}
