// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>
    /// The response schema for a screening configuration.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Sra_ScreeningConfiguration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The reason for the change in the screening configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChangeReason { get; set; }
#nullable restore
#else
        public string ChangeReason { get; set; }
#endif
        /// <summary>Object containing a screening configuration with multiple collections.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_Configuration? Configuration { get; set; }
#nullable restore
#else
        public global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_Configuration Configuration { get; set; }
#endif
        /// <summary>The screening configuration identifier.</summary>
        public Guid? ConfigurationIdentifier { get; set; }
        /// <summary>Timestamp of when the screening configuration was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The unique identifier of the user who created the screening configuration.</summary>
        public Guid? CreatedBy { get; set; }
        /// <summary>The version of the screening configuration.</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_ScreeningConfiguration"/> and sets the default values.
        /// </summary>
        public Sra_ScreeningConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_ScreeningConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_ScreeningConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_ScreeningConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "change_reason", n => { ChangeReason = n.GetStringValue(); } },
                { "configuration", n => { Configuration = n.GetObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_Configuration>(global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_Configuration.CreateFromDiscriminatorValue); } },
                { "configuration_identifier", n => { ConfigurationIdentifier = n.GetGuidValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "created_by", n => { CreatedBy = n.GetGuidValue(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("change_reason", ChangeReason);
            writer.WriteObjectValue<global::PayNow.Libraries.ComplyAdvantageClient.Models.Sra_Configuration>("configuration", Configuration);
            writer.WriteGuidValue("configuration_identifier", ConfigurationIdentifier);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteGuidValue("created_by", CreatedBy);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
