// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace PayNow.Libraries.ComplyAdvantageClient.Models
{
    /// <summary>Classifies a transaction as a specific high-level class of transaction.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransactionClassificationV3
    {
        [EnumMember(Value = "MONETARY")]
        #pragma warning disable CS1591
        MONETARY,
        #pragma warning restore CS1591
    }
}
